name: Documentation

on:
  push:
    branches:
    - master
    paths:
    - Documentation
    - .github/workflows/documentation.yml
  pull_request:
    branches:
    - master
    paths:
    - Documentation
    - .github/workflows/documentation.yml

jobs:
  documentation:
    runs-on: ubuntu-22.04

    steps:
    - name: Install Packages
      run: |
        sudo apt-get -y update
        sudo apt-get -y install asciidoc docbook-xml w3m

    - name: Checkout Sources
      uses: actions/checkout@v4

    - name: Process the Documentation
      id: process_documentation
      working-directory: Documentation
      run: make
