name: Fedora Copr Build
on:
  push:
    paths-ignore:
    - scripts/docker/**
    branches:
    - master
    - current

jobs:
  setup-build:
    name: Submit build to Fedora COPR
    # this seems backwards, but we want to run under Fedora, but Github doesn' support that
    container: fedora:latest
    runs-on: ubuntu-latest

    steps:
    - name: Check out sources
      uses: actions/checkout@v1

    - name: Setup build dependencies in the Fedora container
      run: |
        dnf -y install @development-tools @rpm-development-tools
        dnf -y install copr-cli make

    - name: setup git
      run: |
        git config --global --add safe.directory /__w/subsurface/subsurface
        git config --global --add safe.directory /__w/subsurface/subsurface/libdivecomputer

    - name: atomically create or retrieve the build number
      id: version_number
      if: github.event_name == 'push'
      run: |
        bash scripts/get-atomic-buildnr.sh ${{ github.sha }} ${{ secrets.NIGHTLY_BUILDS }} "CICD-release"
        version=$(cat release-version)
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Setup API token for copr-cli
      env:
        API_TOKEN: ${{ secrets.COPR_TOKEN }}
        API_LOGIN: ${{ secrets.COPR_LOGIN }}
      run: |
        mkdir -p "$HOME/.config"
        cp packaging/copr/config.copr "$HOME/.config/copr"
        sed -i "s/API_TOKEN/$API_TOKEN/;s/API_LOGIN/$API_LOGIN/" "$HOME/.config/copr"

    - name: Checkout googlemaps
      run: |
        cd ..
        git clone https://github.com/subsurface/googlemaps

    - name: run the copr build script
      run: |
        cd ..
        bash -x subsurface/packaging/copr/make-package.sh ${{ github.ref_name }}

