name: Post Release
on:
  push:
    paths-ignore:
    - scripts/docker/**
    branches:
    - master

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  postRelease:
    runs-on: ubuntu-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v4

    # since we are running this step on a pull request, we will skip build numbers in releases
    - name: atomically create or retrieve the build number and assemble release notes
      id: version_number
      run: |
        bash -x ./scripts/get-atomic-buildnr.sh ${{ github.sha }} ${{ secrets.NIGHTLY_BUILDS }} "CICD-release"
        bash scripts/create-releasenotes.sh ${{ github.event.head_commit.id }}
        version=$(cat release-version)
        echo "version=$version" >> $GITHUB_OUTPUT

    # add a file containing the release title so it can be picked up and listed on the release page on our web server
    - name: publish release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version_number.outputs.version }}
        repository: ${{ github.repository_owner }}/nightly-builds
        token: ${{ secrets.NIGHTLY_BUILDS }}
        prerelease: false
        files: release_content_title.txt
        body_path: gh_release_notes.md
