name: Ubuntu Launchpad Build
on:
  push:
    paths-ignore:
    - scripts/docker/**
    branches:
    - master
    - current

jobs:
  push-to-ppa:

    name: Submit build to Ubuntu Launchpad
    runs-on: ubuntu-latest

    steps:
    - name: Check out sources
      uses: actions/checkout@v1

    - name: atomically create or retrieve the build number
      id: version_number
      if: github.event_name == 'push'
      run: |
        bash scripts/get-atomic-buildnr.sh ${{ github.sha }} ${{ secrets.NIGHTLY_BUILDS }} "CICD-release"

    - name: Setup build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y devscripts dput gpg debhelper qt5-qmake cmake

    - name: Setup gpg key token for launchpad
      env:
        GPG_PRIVATE_KEY: ${{ secrets.PPA_SECRET_KEY }}
      run: |
        echo "$GPG_PRIVATE_KEY" > ~/.key
        gpg --import ~/.key

    - name: setup git
      run: |
        git config --global --add safe.directory /__w/subsurface/subsurface
        git config --global --add safe.directory /__w/subsurface/subsurface/libdivecomputer

    - name: Checkout googlemaps
      run: |
        cd ..
        git clone https://github.com/subsurface/googlemaps

    - name: run the launchpad make-package script
      run: |
        cd ..
        bash -x subsurface/packaging/ubuntu/make-package.sh ${{ github.ref_name }}

